# Generated by Django 4.2.5 on 2024-02-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0002_alter_category_options_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
